import { Button } from "@/components/ui/button"
import { HiIcon } from "@/components/hifi/icon"
import { hifiBtn } from "@/components/hifi/button"
import type { Insurer } from "@/features/insurers/types"
import { CopyGlyph, InsurerStatus } from "./shared"

/**
 * Insurer-created success screen (hi-fi `InsurerCreated`) — a centered
 * confirmation with the generated account ID and next-step actions, bound to
 * the freshly-created insurer returned by the create endpoint.
 */
export function InsurerCreated({
  insurer,
  onDone,
  onView,
}: {
  insurer: Insurer
  onDone: () => void
  onView: () => void
}) {
  return (
    <div className="mx-auto my-10 max-w-[460px] text-center">
      <span className="mx-auto mb-[18px] grid size-16 place-items-center rounded-[18px] bg-success-subtle text-success-subtle-foreground [&>svg]:size-[30px]">
        <HiIcon name="checkCircle" />
      </span>
      <h2 className="mb-2 text-[22px] font-bold tracking-[-0.01em]">
        Insurance company created
      </h2>
      <p className="mb-[22px] text-[13.5px] leading-[1.55] text-muted-foreground [&_b]:font-semibold [&_b]:text-foreground">
        The profile for <b>{insurer.name}</b> is live with status{" "}
        <span className="align-middle">
          <InsurerStatus status={insurer.status} />
        </span>
        .
      </p>

      <div className="rounded-[14px] border border-primary/30 bg-primary/[0.04] p-[18px] text-left">
        <span className="text-[10px] font-semibold tracking-[0.06em] text-muted-foreground uppercase">
          Account ID
        </span>
        <div className="mt-[7px] mb-2 flex items-center gap-2.5">
          <code className="font-mono text-[20px] font-bold tracking-[0.04em] text-primary">
            {insurer.accountId}
          </code>
          <CopyGlyph value={insurer.accountId} iconClass="size-[15px]" />
        </div>
        <span className="text-[11.5px] leading-[1.5] text-muted-foreground">
          Generated by the platform — unique and permanent. Use it to reference
          this insurer across modules.
        </span>
      </div>

      <div className="mt-[22px] flex justify-center gap-2.5">
        <Button variant="outline" className={hifiBtn} onClick={onDone}>
          <HiIcon name="plus" />
          Add another
        </Button>
        <Button className={hifiBtn} onClick={onView}>
          <HiIcon name="arrowRight" />
          View profile
        </Button>
      </div>
    </div>
  )
}
