import { Button } from "@/components/ui/button"
import { MiniBadge } from "@/components/console/tagpill"
import { HiIcon } from "@/components/hifi/icon"
import { hifiBtn } from "@/components/hifi/button"
import type { ServiceProvider } from "@/features/service-providers/types"
import { CopyGlyph } from "./shared"

/**
 * Provider-submitted success screen (hi-fi `ProviderCreated`) — a centered
 * confirmation. A newly-submitted provider is created **Pending review**
 * (Inactive) with a permanent account id, and routed to an Approver, so the
 * accent is warning, not success.
 */
export function ProviderCreated({
  provider,
  onList,
  onView,
}: {
  provider: ServiceProvider
  onList: () => void
  onView: () => void
}) {
  return (
    <div className="mx-auto my-10 max-w-[460px] text-center">
      <span className="mx-auto mb-[18px] grid size-16 place-items-center rounded-[18px] bg-warning-subtle text-warning-subtle-foreground [&>svg]:size-[30px]">
        <HiIcon name="clock" />
      </span>
      <h2 className="mb-2 text-[22px] font-bold tracking-[-0.01em]">
        Provider submitted for approval
      </h2>
      <p className="mb-[22px] text-[13.5px] leading-[1.55] text-muted-foreground [&_b]:font-semibold [&_b]:text-foreground">
        The profile for <b>{provider.name}</b> is created with status{" "}
        <span className="align-middle">
          <MiniBadge tone="warning">Pending review</MiniBadge>
        </span>
        . An Approver will review and activate it.
      </p>

      <div className="rounded-[14px] border border-primary/30 bg-primary/[0.04] p-[18px] text-left">
        <span className="text-[10px] font-semibold tracking-[0.06em] text-muted-foreground uppercase">
          Account ID
        </span>
        <div className="mt-[7px] mb-2 flex items-center gap-2.5">
          <code className="font-mono text-[20px] font-bold tracking-[0.04em] text-primary">
            {provider.displayId}
          </code>
          <CopyGlyph value={provider.displayId} iconClass="size-[15px]" />
        </div>
        <span className="text-[11.5px] leading-[1.5] text-muted-foreground">
          Generated by the platform — unique and permanent. The provider stays
          Inactive until approved.
        </span>
      </div>

      <div className="mt-[22px] flex justify-center gap-2.5">
        <Button variant="outline" className={hifiBtn} onClick={onList}>
          <HiIcon name="list" />
          Back to list
        </Button>
        <Button className={hifiBtn} onClick={onView}>
          <HiIcon name="arrowRight" />
          View profile
        </Button>
      </div>
    </div>
  )
}
